name: make binaries

on:
  push:
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    environment: TEST_PYPI_API_TOKEN
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}

    - name: printing
      run: echo secrets.TEST_PYPI_API_TOKEN ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.3.1


    - name: Build wheels
      env:
        CIBW_BUILD: cp3*
        CIBW_SKIP: cp31*
      run: python -m cibuildwheel --output-dir dist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
