name: make binaries

on:
  push:
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/local/opt/llvm/bin/clang
      CXX: /usr/local/opt/llvm/bin/clang++
    environment: TEST_PYPI_API_TOKEN
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}

    - name: Prepare os
      if: matrix.os == 'macOS-latest'
      run: |      
        echo fffffffffffffffffffffff
        brew install llvm libomp
        ls /usr/local/lib/libomp.dylib
        ls /usr/local/Cellar/libomp/13.0.1/
    
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel


    - name: Build wheels
      env:
        CIBW_BUILD: cp38*
        CIBW_SKIP: cp31*
      run: python -m cibuildwheel --output-dir dist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
