name: make docs and push to the pages branch

on:
  push:
    branches:
      - master

jobs:
  make_docs:
    name: Updating docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']    
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    
    - name: installing
      run: |
            pip install --upgrade pip
            pip install --upgrade build
            python -m build -C--global-option=build_ext -C--global-option=--inplace
            pip install sphinx
            pip install sphinx_rtd_theme

    - name: make the docs
      run: |
            cd docs
            sphinx-apidoc -o . ../snipar/
            make html
    
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: pages # The branch name where you want to push the assets
        FOLDER: docs # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message