name: Python package

on:
  push:
    branches: 
    - master
    - tidy
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7']
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.3.1

    - name: Build wheels
      env:
        CIBW_BUILD: cp37*
        CIBW_SKIP: cp31*
      run: python -m cibuildwheel --output-dir dist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
